name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean clean compileGroovy compileJava
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-folder
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: build-folder
      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport
      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: build-folder
      - name: Build fat jar
        run: ./gradlew shadowJar
      - name: Publish Docker Image to GitHub Package Registry (GPR)
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'unfima'
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: './'
          BRANCH_TAG: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deployOnGoogleCloud:
    if: contains(github.ref, 'master') # Only do that on push to master
    needs: [package, test]
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: aqueous-helper-268113
      RUN_REGION: us-central1
      SERVICE_NAME: unfima
    steps:
      - name: Authenticate at GitHub releases
        run: docker login -u nijin22 -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
      - name: Download image from GitHub
        run: docker pull docker.pkg.github.com/nijin22/unnamed-finance-manager/unfima:${GITHUB_REF##*/}
      - name: Tag for GCR
        run: docker tag docker.pkg.github.com/nijin22/unnamed-finance-manager/unfima:${GITHUB_REF##*/} gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${GITHUB_REF##*/}
      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{secrets.GCLOUD_EMAIL}}
          service_account_key: ${{secrets.GCLOUD_CREDENTIALS}}
      - name: Configure gcloud CLI
        run: >
          gcloud config set project $PROJECT_ID;
          gcloud auth configure-docker;
      - name: Push to GCR
        run: docker push gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${GITHUB_REF##*/}
      - name: Deploy service to Google Cloud Run
        run: >
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${GITHUB_REF##*/} \
            --platform managed

